<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="action.surefire.report.calc.CalcUtilsTest" time="0.001" tests="2" errors="0" skipped="0" failures="2">
  <testcase name="test error handling" classname="action.surefire.report.calc.CalcUtilsTest" time="0">
    <failure message="unexpected exception type thrown; expected:&lt;java.lang.IllegalStateException&gt; but was:&lt;java.lang.IllegalArgumentException&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: unexpected exception type thrown; expected:<java.lang.IllegalStateException> but was:<java.lang.IllegalArgumentException>
	at action.surefire.report.calc.CalcUtilsTest.test error handling(CalcUtilsTest.kt:27)
Caused by: java.lang.IllegalArgumentException: Amount must have max 2 non-zero decimal places
	at action.surefire.report.calc.CalcUtilsTest.scale(CalcUtilsTest.kt:31)
	at action.surefire.report.calc.CalcUtilsTest.access$scale(CalcUtilsTest.kt:9)
	at action.surefire.report.calc.CalcUtilsTest.test error handling(CalcUtilsTest.kt:27)
]]></failure>
  </testcase>
  <testcase name="test scale" classname="action.surefire.report.calc.CalcUtilsTest" time="0.001">
    <failure message="&#10;Expected: &lt;100.10&gt;&#10;     but: was &lt;100.11&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: 

Expected: <100.10>
     but: was <100.11>
	at action.surefire.report.calc.CalcUtilsTest.test scale(CalcUtilsTest.kt:15)
]]></failure>
  </testcase>
</testsuite>